### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: begin 10, end 9, length 9

### ISSUE THREAD

**Issue by cgw2023** [ruCakeMC/framedImage#5]
folia-bundler-1.20.1-R0.1-SNAPSHOT-reobf

after install framedimage-1.5

error will occur, players cannot login

```/127.0.0.1:55828 lost connection: Internal Exception: java.lang.StringIndexOutOfBoundsException: begin 10, end 9, length 9
```

**Comment by JNNGL** [comment]
send logs

**Comment by cgw2023** [comment]
https://paste.denizenscript.com/View/111335

**Comment by JNNGL** [comment]
Fixed in 9192e5f

**Comment by Tuurngait** [comment]
... there's a catch. On the Geyser-BungeeCord version, the problem persists.
